### ISSUE TITLE
FFI::NullPointerError on list_subnet_option_values

### ISSUE THREAD

**Issue by mporrato** [witlessbird/ruby-dhcpsapi#5]
```
irb(main):001:0> require 'dhcpsapi'
=> true
irb(main):002:0> api=DhcpsApi::Server::new('172.16.30.93')
=> #<DhcpsApi::Server:0x0000000003a30b30 @server_ip_address="172.16.30.93">
irb(main):003:0> api.list_subnet_option_values('172.42.0.0')
=> [{:option_id=>3, :value=>[{:option_type=>4, :element=>"172.42.3.254"}]}, {:option_id=>6, :value=>[{:option_type=>4, :element=>"172.16.30.213"}, {:option_type=>4, :element=>"172.16.13.39"}]}, {:option_id=>15, :value=>[{:option_type=>5, :element=>"foo.bar.baz.example.com"}]}, {:option_id=>51, :value=>[{:option_type=>2, :element=>691200}]}]
irb(main):004:0> api.list_subnet_option_values('172.42.4.0')
FFI::NullPointerError: invalid memory read at address=0x0000000000000000
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/data_structures.rb:508:in `[]'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/data_structures.rb:508:in `as_ruby_struct'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/option_value.rb:439:in `dhcp_enum_option_values_v5'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:79:in `block in retrieve_items'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `loop'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `retrieve_items'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/option_value.rb:290:in `list_subnet_option_values'
        from (irb):4
        from C:/Ruby24-x64/bin/irb.cmd:19:in `<main>'
irb(main):005:0>
```

**Comment by dmitri-d** [comment]
Any chance you could check and report here the value of ```error``` variable right before https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/option_value.rb#L430? ```puts "error: #{error}"``` should do the trick.

**Comment by mporrato** [comment]
Thanks for the suggestion.
The error code is 234: seems like the DLL is asking for more room for the results.
I changed the preferred_maximum argument value in the call at https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/option_value.rb#L293 from 1024 to 4096 and it now works.

Edit: Actually the minimum value seems to be 1032. Anything lower triggers the error in my environment.
