### ISSUE TITLE
Error when importing a subnet

### ISSUE THREAD

**Issue by martux69** [witlessbird/ruby-dhcpsapi#6]
Hi,
when I try to import a subnet I get this error:

"uninitialized constant DhcpsApi::Win2008::Subnet. Did you mean?  DhcpsApi::Subnet"

The smart proxy is running on the same server providing the DHCP service.
The server is running with Windows 2012R2, Foreman and the smart proxy are running in version 1.18, dhcpsapi has version 0.0.11 .

Must I configure somewhere the windows version I use ? If I see it right in the code there is no differentiation for accessing subnet functions between 2008 and 2012 ?

What can I do for a successful action ?

Any hints for me are welcome :-)

Best regards

Martin

**Comment by dmitri-d** [comment]
Hey there,
This is pretty odd. Is there anything in the logs, especially around startup?

The differentiation between Windows versions is due to some functionality being only available on Windows 2012 (free ip related calls, if I remember correctly). Windows 2008 calls should always be available.

Api initialization happens here: https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/server.rb#L29. Windows 2008 calls are being handled first (subnet-related bindings are here: https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/win2008/subnet.rb).

 -Dmitri

**Comment by martux69** [comment]
Hi Dmitri,
I cannot see something special in the log.
When I try to get a free ip address, the message is:

29 Jul 12:25 | WARN | The specified subnet 172.24.20.0 does not exist on the DHCP server
-- | -- | --
29 Jul 12:25 | INFO | 172.30.110.11 - - [29/Jul/2019:12:25:58 +0200] "GET /dhcp/172.24.20.0/unused_ip HTTP/1.1" 200 11 0.0013

But the subnet exists on the DHCP Server:
![Screenshot_20190729_122846](https://user-images.githubusercontent.com/5789285/62059881-608e0e00-b224-11e9-91e3-ef3d714fe583.png)

Perhaps it belongs to the name of the area ? 
Is it possible to test the DHCP API by using curl ?

Best regards
Martin

**Comment by martux69** [comment]
Hi Dmitri,
I try it with irb and get this result:
irb
irb(main):001:0> require 'dhcpsapi'
=> true
irb(main):002:0> api=DhcpsApi::Server::new('192.168.100.17')
=> #<DhcpsApi::Server:0x000055cac4e331b0 @server_ip_address="192.168.100.17">
irb(main):003:0> api.list_clients('192.168.100.0')
Traceback (most recent call last):
        7: from /usr/bin/irb:11:in `<main>'
        6: from (irb):3
        5: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/client.rb:33:in `list_clients'
        4: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `retrieve_items'
        3: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `loop'
        2: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:79:in `block in retrieve_items'
        1: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/client.rb:289:in `dhcp_v4_enum_subnet_clients'
NoMethodError (undefined method `DhcpV4EnumSubnetClients' for DhcpsApi::Client:Module)
irb(main):004:0>
 Also a list of subnets fails:
irb(main):005:0> api.list_subnets
Traceback (most recent call last):
        8: from /usr/bin/irb:11:in `<main>'
        7: from (irb):5
        6: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/subnet.rb:15:in `list_subnets'
        5: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/subnet.rb:108:in `enum_subnets'
        4: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `retrieve_items'
        3: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:78:in `loop'
        2: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/common.rb:79:in `block in retrieve_items'
        1: from /var/lib/gems/2.5.0/gems/dhcpsapi-0.0.11/lib/dhcpsapi/subnet.rb:137:in `dhcp_enum_subnets'
NameError (uninitialized constant DhcpsApi::Win2008::Subnet)
Did you mean?  DhcpsApi::Subnet
irb(main):006:0>
It seems to me that there is a mismatch with the Windows versions. Perhaps Windows2012R2 needs additional resources ?

Best regards
Martin

**Comment by dmitri-d** [comment]
You can try checking what api have been detected:

```
DhcpsApi::Server::new('192.168.100.17').api_level
```

The constants the call returns are defined here: https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/server.rb#L3. I suspect it's going to be ```DHCPS_NONE```

You can then try printing out the exception here: https://github.com/dmitri-d/ruby-dhcpsapi/blob/master/lib/dhcpsapi/server.rb#L47 which might help with troubleshooting. 

Have you tried asking for help in #theforeman? I no longer have access to Windows or involved with smart-proxy...

**Comment by martux69** [comment]
The output is
irb(main):008:0> puts DhcpsApi::Server::new('192.168.100.17').api_level
#<Object:0x000055fbe5824268>
=> nil
irb(main):009:0>
Thank you for helping so far, I will try to ask in #theforeman now.
